import { buildSeedIdea, type SeedIdeaInput, type SeedSource } from "./build-seed-idea";

const ACCESSED = "2026-09-26";

function sources(extra: SeedSource[]): SeedSource[] {
  return [
    {
      id: 1,
      title: "Sample score inputs",
      url: "/methodology#scores",
      publisher: "IdeaDaily",
      accessed: ACCESSED,
      note: "Volume, growth, quote counts, and competitor counts on this record are sample priors. They are not live measurements.",
      sample: true,
    },
    ...extra,
  ];
}

const ideas: SeedIdeaInput[] = [
  {
    slug: "quotelatch",
    title: "QuoteLatch",
    summary: "A quoting desk that turns a homeowner’s panel photo into a deposit-ready electrical quote, using the shop’s own price book.",
    daysAgo: 0,
    tags: ["Open timing", "Narrow buyer", "Light MVP", "Trade workflow"],
    keyword: "electrician quote software",
    volume: 14000,
    growthPct: 55,
    inputs: {
      monthlyVolume: 14000,
      growthPct: 55,
      competitorCount: 3,
      painQuoteCount: 2,
      painSeverityAvg: 4.5,
      buildWeeks: 3,
      capitalBand: "low",
      regulatoryLoad: 0,
      dependencyRisk: 1,
      timingSignals: 3,
    },
    category: "Vertical software",
    market: "B2B",
    capitalBand: "low",
    revenueSymbols: "$$",
    arrLabel: "Illustrative band only",
    arrNote: "No ARR figure is claimed. A sample model of 80 shops is arithmetic, not a forecast. {{s1}}",
    gtm: 6,
    gtmNote: "Start at two wholesale counters and one public trade forum. No member counts are claimed.",
    target: "Owners of residential electrical shops with one to eight technicians.",
    competitor: "Field-service suites cover scheduling. They are a weak fit for a photo-plus-price-book quote. Confirm names with Idea Agent before you cite them.",
    pitch: `A residential electrician often prices the next job from a photo that arrives after dinner. The panel, the run, the existing fixture — the homeowner already sent the picture. The owner rebuilds the scope from memory, then either underprices the materials or answers so late that the lead has called someone else.

QuoteLatch is a quoting desk for that shop, not a marketplace and not a generic invoicing app. The owner forwards the thread. The photos sit beside the shop’s own price book: service call, panel upgrade, EV charger, fixture swap, with allowances and exclusions the shop actually uses. The customer gets a one-page quote and can leave a card deposit. The technician is not asked to learn a new CRM.

The first version is deliberately small. An inbox, a price book with twenty lines, a PDF, and a deposit link. No dispatch board, no inventory, no customer portal. If the owner will not send this quote, a larger app will not fix the habit.

A sample revenue sketch, not a forecast: 80 shops at a price you have not earned yet is not a business. Set the price from the first ten deposits, then write the number down. {{s1}} The channels to try first are wholesale counters, trade-school job boards, and the public electrician forums linked below. We do not print member counts we have not measured. {{s2}}`,
    channels: [
      { platform: "Forum", name: "Electrician Talk", url: "https://www.electriciantalk.com/", note: "Public forum index. Member count not measured.", sample: true },
      { platform: "Search", name: "YouTube results for electrician quoting", url: "https://www.youtube.com/results?search_query=electrician+quoting+jobs", note: "Search page only. No view counts are claimed.", sample: true },
      { platform: "Discussion", name: "Hacker News search", url: "https://hn.algolia.com/?q=field%20service%20quoting", note: "Public search. Not a citation of a specific comment.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A one-page price-book starter for the twenty jobs a residential shop prices every week." },
      { tier: "Frontend", price: "Set with the first ten shops", detail: "You build the quote with them on a call and send the PDF the same day." },
      { tier: "Core", price: "Seat, after the manual offer sells", detail: "Inbox, price book, PDF, and deposit link for one shop." },
    ],
    whyNow: `Card deposits are now a normal step in field-service tools, so a quote can collect a commitment without a merchant-account project. {{s3}} Homeowners already describe the job with a phone photo, which means the input channel exists. {{s2}} Neither observation is a market-size claim. They are reasons the MVP can stay small.`,
    proof: `Sample mode does not invent forum quotes. The pain on this page is the repeated chore described in the pitch, and the quote-count input is a sample prior of 2. {{s1}} Before you raise the pain score, attach verbatim lines and the URLs they came from. Communities to read first are listed under Community signals. The obvious risk is that shops already live inside a suite they will not leave for a single screen.`,
    marketGap: `Scheduling suites are built around the work order that exists after the price is agreed. The gap, if it holds up in interviews, is the ten minutes between a blurry photo and a number the shop will stand behind. Do not name a winner until Idea Agent returns pages you have opened. {{s1}}`,
    executionPlan: `Day 1: sit with one shop and write their twenty price lines and the exclusions they say out loud. Days 2–4: send five quotes as PDFs you assemble by hand. Days 5–7: software only for the steps you repeated — attach photos, pick lines, take a deposit. Kill dispatch, inventory, and a consumer app.`,
    uniqueness: 7,
    value: 8,
    triangle: { audience: 6, community: 7, offer: 8 },
    frameworkNote: "Position Map marks this as a narrow tool with a clear artifact. Signal Triangle is a reviewer mark, not a survey.",
    requirements: {
      skills: { tech: 3, sales: 3, design: 2, domain: 3 },
      weeklyHours: 15,
      capitalBand: "low",
      risk: "low",
      model: "b2b",
      motion: "saas",
      industries: ["trades"],
      mvpWeeks: 3,
      salesIntensity: 4,
      regulatoryLoad: 0,
    },
    sources: sources([
      { id: 2, title: "Electrician Talk", url: "https://www.electriciantalk.com/", publisher: "Electrician Talk", accessed: ACCESSED, note: "Public community homepage. No posts were scraped and no counts are claimed.", sample: true },
      { id: 3, title: "Stripe Checkout documentation", url: "https://docs.stripe.com/payments/checkout", publisher: "Stripe", accessed: ACCESSED, note: "Cited only to show that a hosted card payment is a documented product step, not that shops use it.", sample: false },
    ]),
    brief: {
      title: "QuoteLatch",
      slug: "quotelatch",
      oneLiner: "Turn a homeowner’s panel photo into a deposit-ready quote using the shop’s own price book.",
      customer: "Owners of residential electrical shops with one to eight technicians.",
      problem: "Quotes are rebuilt at night from a texted photo, and the shop either misprices the job or answers too late.",
      mvp: ["Photo inbox", "Twenty-line price book", "One-page PDF quote", "Card deposit"],
      stack: "Next.js, Postgres, Stripe",
      pricing: "Do not print a price. The manual offer sets it.",
      outOfScope: ["Dispatch board", "Inventory", "Consumer marketplace", "Native apps"],
    },
  },
  {
    slug: "dockboard",
    title: "Dockboard",
    summary: "A shared appointment board for loading docks used by several tenants in one warehouse.",
    daysAgo: 3,
    tags: ["Operations", "Multi-tenant", "B2B"],
    keyword: "warehouse dock scheduling",
    volume: 6200,
    growthPct: 28,
    inputs: {
      monthlyVolume: 6200,
      growthPct: 28,
      competitorCount: 5,
      painQuoteCount: 1,
      painSeverityAvg: 4,
      buildWeeks: 5,
      capitalBand: "low",
      regulatoryLoad: 0,
      dependencyRisk: 1,
      timingSignals: 2,
    },
    category: "Operations",
    market: "B2B",
    capitalBand: "low",
    revenueSymbols: "$$",
    arrLabel: "Unset",
    arrNote: "Price per building, not per carrier. No revenue figure until a building manager pays. {{s1}}",
    gtm: 5,
    gtmNote: "Sell to the building manager, not to each carrier. One city at a time.",
    target: "Managers of multi-tenant warehouses with two to six shared dock doors.",
    competitor: "Yard-management products assume a single operator owns the yard. Confirm that with linked product pages before you repeat it.",
    pitch: `When several tenants share a dock, the calendar lives in a group text. Carriers arrive on top of each other, and the smallest tenant loses the hour.

Dockboard is a door calendar for one building. The manager owns the board. Each tenant sees only their slots. A carrier gets a link with the door and the time, and nothing else.

The MVP is the board, a conflict warning, and a link. Gate hardware, cameras, and a marketplace of carriers are out.`,
    channels: [
      { platform: "Discussion", name: "Hacker News search for warehouse scheduling", url: "https://hn.algolia.com/?q=warehouse%20scheduling", note: "Public search page. No comment is quoted.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A one-week paper grid for four dock doors." },
      { tier: "Frontend", price: "Per building, after a pilot week", detail: "You run the board for them in a spreadsheet for five days." },
      { tier: "Core", price: "Building subscription", detail: "Shared calendar, conflict warnings, carrier links." },
    ],
    whyNow: `Small warehouses already coordinate by text because the building, not a single carrier, owns the constraint. A single-tenant yard system does not match that buyer. {{s1}} This is a structural guess to test, not a trend statistic.`,
    proof: `No verbatim complaints are attached. Treat the pain score as a prior. {{s1}} The failure mode is a building manager who will not make tenants use a new link.`,
    marketGap: `The likely gap is the shared door, not the truck. Verify it by listing the scheduling tool each tenant already pays for and showing that none of them can see the other tenants. {{s1}}`,
    executionPlan: `Spend two mornings at one building. Photograph the current board or the group text (with permission). Run the next week in a shared sheet. Only then build the conflict rule you actually used.`,
    uniqueness: 7,
    value: 7,
    triangle: { audience: 5, community: 4, offer: 7 },
    frameworkNote: "A tight offer with a thin public community. Distribution is local and physical.",
    requirements: {
      skills: { tech: 3, sales: 4, design: 2, domain: 2 },
      weeklyHours: 20,
      capitalBand: "low",
      risk: "medium",
      model: "b2b",
      motion: "saas",
      industries: ["logistics"],
      mvpWeeks: 4,
      salesIntensity: 4,
      regulatoryLoad: 0,
    },
    sources: sources([
      { id: 2, title: "Hacker News search", url: "https://hn.algolia.com/?q=warehouse%20scheduling", publisher: "Algolia HN", accessed: ACCESSED, note: "Search page. Not a measured complaint count.", sample: true },
    ]),
    brief: {
      title: "Dockboard",
      slug: "dockboard",
      oneLiner: "A shared dock-door calendar for multi-tenant warehouses.",
      customer: "Building managers at warehouses with two to six shared doors.",
      problem: "Tenants book the same door because the calendar is a group text.",
      mvp: ["Door calendar", "Conflict warning", "Carrier link"],
      stack: "Next.js, Postgres",
      pricing: "Per building, set after one paid pilot.",
      outOfScope: ["Gate hardware", "Cameras", "Carrier marketplace"],
    },
  },
  {
    slug: "kennelnote",
    title: "KennelNote",
    summary: "A structured handoff for the overnight tech at an independent vet clinic.",
    daysAgo: 6,
    tags: ["Clinics", "Handoff", "B2B"],
    keyword: "vet clinic shift handoff",
    volume: 4100,
    growthPct: 22,
    inputs: {
      monthlyVolume: 4100,
      growthPct: 22,
      competitorCount: 4,
      painQuoteCount: 2,
      painSeverityAvg: 4,
      buildWeeks: 3,
      capitalBand: "low",
      regulatoryLoad: 1,
      dependencyRisk: 2,
      timingSignals: 2,
    },
    category: "Clinics",
    market: "B2B",
    capitalBand: "low",
    revenueSymbols: "$",
    arrLabel: "Unset",
    arrNote: "Clinic software budgets are real, but this page does not claim a share of them. {{s1}}",
    gtm: 5,
    gtmNote: "Sell through relief techs who work in several clinics, not through a cold list.",
    target: "Independent vet clinics with an overnight or late tech and no enterprise hospital system.",
    competitor: "Practice-management systems store the record. The handoff at 10pm is often a sticky note. Verify before naming a vendor.",
    pitch: `The overnight tech inherits a cage, a dose, and a sentence someone meant to write down. KennelNote is a five-field handoff: patient, what changed, what to watch, who to call, and when the note expires.

It is not a medical record. It does not diagnose. The MVP is a shared list the closing tech fills in sixty seconds and the opening tech clears in the morning.`,
    channels: [
      { platform: "Search", name: "YouTube results for vet tech night shift", url: "https://www.youtube.com/results?search_query=vet+tech+night+shift", note: "Search page. No videos are quoted.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A printable end-of-shift card with the five fields." },
      { tier: "Frontend", price: "Clinic setup fee", detail: "You load last month’s patients they choose to share and run the card for a week." },
      { tier: "Core", price: "Per clinic", detail: "Shared list, expiry, and a morning clear." },
    ],
    whyNow: `Relief staffing means the person opening the clinic may not have been there at close. The handoff has to stand alone. {{s1}} That is an operating change, not a search-volume claim.`,
    proof: `No clinical quotes are fabricated here. Regulatory load is marked at 1 because the note must not pretend to be a medical record. {{s1}}`,
    marketGap: `Record systems are where the chart lives. The gap to test is the sixty-second note that is useless if it takes a login, a patient search, and twelve fields. {{s1}}`,
    executionPlan: `Shadow one close and one open. Count the fields they actually say. Ship a phone page with those fields only. Stop if the tech will not fill it in without you in the room.`,
    uniqueness: 6,
    value: 7,
    triangle: { audience: 5, community: 5, offer: 7 },
    frameworkNote: "Offer clarity is high if the five fields stay frozen.",
    requirements: {
      skills: { tech: 3, sales: 3, design: 3, domain: 3 },
      weeklyHours: 15,
      capitalBand: "low",
      risk: "medium",
      model: "b2b",
      motion: "saas",
      industries: ["clinics"],
      mvpWeeks: 3,
      salesIntensity: 3,
      regulatoryLoad: 1,
    },
    sources: sources([
      { id: 2, title: "YouTube search", url: "https://www.youtube.com/results?search_query=vet+tech+night+shift", publisher: "YouTube", accessed: ACCESSED, note: "Search URL only.", sample: true },
    ]),
    brief: {
      title: "KennelNote",
      slug: "kennelnote",
      oneLiner: "A five-field overnight handoff for independent vet clinics.",
      customer: "Independent vet clinics with a late or overnight tech.",
      problem: "The opening tech inherits a patient without a note that stands alone.",
      mvp: ["Five-field note", "Expiry", "Morning clear"],
      stack: "Next.js, Postgres",
      pricing: "Per clinic, after a paid setup week.",
      outOfScope: ["Medical records", "Diagnoses", "Billing"],
    },
  },
  {
    slug: "menumargin",
    title: "Menu Margin",
    summary: "Recipe costing for independent restaurants that still price plates in a spreadsheet.",
    daysAgo: 12,
    tags: ["Hospitality", "Costing", "B2B"],
    keyword: "restaurant recipe costing",
    volume: 9800,
    growthPct: 18,
    inputs: {
      monthlyVolume: 9800,
      growthPct: 18,
      competitorCount: 7,
      painQuoteCount: 2,
      painSeverityAvg: 3.5,
      buildWeeks: 6,
      capitalBand: "low",
      regulatoryLoad: 0,
      dependencyRisk: 1,
      timingSignals: 2,
    },
    category: "Hospitality",
    market: "B2B",
    capitalBand: "low",
    revenueSymbols: "$$",
    arrLabel: "Unset",
    arrNote: "Crowded category. Do not print a market size. {{s1}}",
    gtm: 4,
    gtmNote: "Harder go-to-market because costing tools already exist. Win a single cuisine and a supplier relationship.",
    target: "Independent restaurants with one site and a menu that changes weekly.",
    competitor: "Several costing apps already exist. The gap has to be a workflow they refuse, not a claim that the category is empty.",
    pitch: `Menu Margin costs a plate from the invoice the chef already has, then shows which dishes fell below the shop’s own margin rule when a supplier price moved.

It is a crowded job. The only version worth building is the one a single kitchen will update on Monday morning without a consultant. If they will not, do not add inventory, reservations, or a POS integration.`,
    channels: [
      { platform: "Discussion", name: "Hacker News search for restaurant software", url: "https://hn.algolia.com/?q=restaurant%20software", note: "Search page only.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A margin card for twelve dishes." },
      { tier: "Frontend", price: "Menu teardown", detail: "You cost the current menu once from their invoices." },
      { tier: "Core", price: "Monthly, if they ask for the update", detail: "Invoice in, dish margin out, alert when a plate breaks the rule." },
    ],
    whyNow: `Supplier prices move often enough that a quarterly spreadsheet lies. That is a reason to refresh a cost, not a reason to assume restaurants will switch tools. {{s1}}`,
    proof: `Competitor count is a sample prior of 7, which already pulls the opportunity score down. {{s1}} Read current product pages before you claim a gap.`,
    marketGap: `The testable gap is Monday-morning upkeep for a single site, not “restaurants need software.” If a current tool already does that in fifteen minutes, pass. {{s1}}`,
    executionPlan: `Cost one menu by hand. Time it. Then cut every step you did not repeat. Ignore POS integrations until a chef has paid for the teardown.`,
    uniqueness: 4,
    value: 6,
    triangle: { audience: 7, community: 5, offer: 5 },
    frameworkNote: "Position Map sits near Category Leader: real value, crowded space.",
    requirements: {
      skills: { tech: 3, sales: 3, design: 2, domain: 4 },
      weeklyHours: 20,
      capitalBand: "low",
      risk: "low",
      model: "b2b",
      motion: "service",
      industries: ["hospitality"],
      mvpWeeks: 5,
      salesIntensity: 3,
      regulatoryLoad: 0,
    },
    sources: sources([]),
    brief: {
      title: "Menu Margin",
      slug: "menumargin",
      oneLiner: "Invoice-to-plate costing for a single independent restaurant.",
      customer: "Independent restaurants with one site and a weekly menu change.",
      problem: "Plate prices drift when a spreadsheet is updated late.",
      mvp: ["Invoice lines", "Dish margin", "Alert when a plate breaks the house rule"],
      stack: "Next.js, Postgres",
      pricing: "Charge for the teardown first.",
      outOfScope: ["POS integration", "Reservations", "Inventory marketplace"],
    },
  },
  {
    slug: "permitping",
    title: "PermitPing",
    summary: "Status alerts for small contractors waiting on a permit office that does not email them.",
    daysAgo: 18,
    tags: ["Trades", "Local government", "Alerts"],
    keyword: "contractor permit tracking",
    volume: 7300,
    growthPct: 36,
    inputs: {
      monthlyVolume: 7300,
      growthPct: 36,
      competitorCount: 4,
      painQuoteCount: 1,
      painSeverityAvg: 4,
      buildWeeks: 8,
      capitalBand: "medium",
      regulatoryLoad: 2,
      dependencyRisk: 3,
      timingSignals: 2,
    },
    category: "Trades",
    market: "B2B",
    capitalBand: "medium",
    revenueSymbols: "$$",
    arrLabel: "Unset",
    arrNote: "Depends on public permit portals that can change without notice. {{s1}}",
    gtm: 4,
    gtmNote: "City by city. Do not promise national coverage.",
    target: "Small general contractors pulling permits in one metro.",
    competitor: "Some cities have a portal and no alert. Third-party trackers exist in a few metros. Check the specific city.",
    pitch: `PermitPing watches a public permit number and tells the contractor when the status string changes. It does not file the permit and it does not speak for the city.

The hard part is not the email. It is the portal. Build one city, with a manual fallback when the page moves, or do not start.`,
    channels: [
      {
        platform: "Directory",
        name: "USA.gov local governments",
        url: "https://www.usa.gov/local-governments",
        note: "Public directory. Not a claim about any one city’s API.",
        sample: false,
      },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A checklist for reading one city’s permit status page." },
      { tier: "Frontend", price: "Per active permit, concierge", detail: "A person checks the page daily for a month." },
      { tier: "Core", price: "City subscription", detail: "Alerts for one metro, with a human fallback when the portal changes." },
    ],
    whyNow: `Contractors already refresh the same status page. An alert is valuable only while that page stays readable. {{s1}} Dependency risk is intentionally high.`,
    proof: `Do not quote a contractor you have not interviewed. The dependency score is the point of this idea: the city can break it. {{s1}}`,
    marketGap: `National construction suites do not wake someone up when a single city’s status line changes. Whether a local tool already does is a city-level question. {{s1}}`,
    executionPlan: `Pick one city. List every permit status you can see without a login. Run the concierge for ten permits. Automate only the page you successfully read for two weeks.`,
    uniqueness: 6,
    value: 7,
    triangle: { audience: 6, community: 4, offer: 6 },
    frameworkNote: "Value is real and so is the platform dependency. Buildability is supposed to look heavy.",
    requirements: {
      skills: { tech: 4, sales: 3, design: 2, domain: 3 },
      weeklyHours: 25,
      capitalBand: "medium",
      risk: "high",
      model: "b2b",
      motion: "saas",
      industries: ["trades"],
      mvpWeeks: 8,
      salesIntensity: 3,
      regulatoryLoad: 2,
    },
    sources: sources([
      { id: 2, title: "USA.gov local governments", url: "https://www.usa.gov/local-governments", publisher: "USA.gov", accessed: ACCESSED, note: "Public directory. Not a permit dataset.", sample: false },
    ]),
    brief: {
      title: "PermitPing",
      slug: "permitping",
      oneLiner: "Email a contractor when one city’s permit status changes.",
      customer: "Small general contractors in a single metro.",
      problem: "They refresh a public status page that does not notify them.",
      mvp: ["One city", "Status diff", "Email alert", "Manual fallback"],
      stack: "Next.js, Postgres, a scheduled fetch",
      pricing: "Sell the concierge month before the scraper.",
      outOfScope: ["Filing permits", "National coverage", "Plan review"],
    },
  },
  {
    slug: "crateday",
    title: "CrateDay",
    summary: "Packing lists and member pauses for small CSA farms.",
    daysAgo: 24,
    tags: ["Food", "Subscriptions", "B2C ops"],
    keyword: "csa subscription software",
    volume: 5400,
    growthPct: 15,
    inputs: {
      monthlyVolume: 5400,
      growthPct: 15,
      competitorCount: 4,
      painQuoteCount: 1,
      painSeverityAvg: 3.5,
      buildWeeks: 4,
      capitalBand: "low",
      regulatoryLoad: 0,
      dependencyRisk: 1,
      timingSignals: 2,
    },
    category: "Food",
    market: "B2C",
    capitalBand: "low",
    revenueSymbols: "$",
    arrLabel: "Unset",
    arrNote: "Farms pay slowly. Prove a packing-morning habit before a subscription pitch. {{s1}}",
    gtm: 6,
    gtmNote: "Farmers’ market conversations and extension newsletters. One region.",
    target: "CSA farms with 40 to 250 members and a weekly box.",
    competitor: "Generic subscription tools do not know a box share. Farm-specific tools exist — list them with links before claiming a gap.",
    pitch: `CrateDay answers two questions on packing morning: who paused, and what goes in the remaining boxes. Members change a pause by Wednesday. The farm prints one list.

Payments can stay where they are. The product is the list.`,
    channels: [
      { platform: "Search", name: "USDA CSA overview", url: "https://www.nal.usda.gov/afsic/community-supported-agriculture", note: "Public explainer that CSAs exist. No market size is taken from it.", sample: false },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A Wednesday pause policy you can paste into a newsletter." },
      { tier: "Frontend", price: "Harvest season setup", detail: "We load the member list and run the first four weeks with you." },
      { tier: "Core", price: "Per season", detail: "Pauses, packing list, and a member link." },
    ],
    whyNow: `The box already goes out on a fixed day. Software only helps if it is finished before that morning. {{s2}}`,
    proof: `The USDA page confirms the model exists. It is not a demand statistic. {{s2}} {{s1}}`,
    marketGap: `The gap to test is the pause cutoff, not “farms need an app.” If their spreadsheet already locks on Wednesday, this is a pass. {{s1}}`,
    executionPlan: `Run four packing mornings with one farm using a sheet that locks Wednesday at noon. Build the member link only after they refuse to go back to the sheet.`,
    uniqueness: 6,
    value: 6,
    triangle: { audience: 5, community: 6, offer: 7 },
    frameworkNote: "A seasonal offer. Do not model it as monthly SaaS until a farm asks for that.",
    requirements: {
      skills: { tech: 3, sales: 3, design: 2, domain: 3 },
      weeklyHours: 12,
      capitalBand: "low",
      risk: "low",
      model: "b2c",
      motion: "saas",
      industries: ["food"],
      mvpWeeks: 4,
      salesIntensity: 3,
      regulatoryLoad: 0,
    },
    sources: sources([
      { id: 2, title: "USDA NAL: Community Supported Agriculture", url: "https://www.nal.usda.gov/afsic/community-supported-agriculture", publisher: "USDA National Agricultural Library", accessed: ACCESSED, note: "Background page. No membership or revenue figures are copied from it.", sample: false },
    ]),
    brief: {
      title: "CrateDay",
      slug: "crateday",
      oneLiner: "Wednesday pauses and a Thursday packing list for a small CSA.",
      customer: "CSA farms with 40 to 250 members.",
      problem: "The packing list is wrong because pauses arrive in five different channels.",
      mvp: ["Member pause link", "Wednesday lock", "Printable packing list"],
      stack: "Next.js, Postgres",
      pricing: "Per season, after four assisted weeks.",
      outOfScope: ["Payments", "Delivery routing", "Farm marketplace"],
    },
  },
  {
    slug: "studiohold",
    title: "StudioHold",
    ideaType: "APP",
    summary: "Deposits and a no-show rule for private music teachers.",
    daysAgo: 30,
    tags: ["Education", "Bookings", "Solo"],
    keyword: "music teacher scheduling deposits",
    volume: 8800,
    growthPct: 12,
    inputs: {
      monthlyVolume: 8800,
      growthPct: 12,
      competitorCount: 8,
      painQuoteCount: 1,
      painSeverityAvg: 3,
      buildWeeks: 3,
      capitalBand: "none",
      regulatoryLoad: 0,
      dependencyRisk: 1,
      timingSignals: 1,
    },
    category: "Education",
    market: "B2C",
    capitalBand: "none",
    revenueSymbols: "$",
    arrLabel: "Unset",
    arrNote: "Teachers are a crowded software audience. A no-show rule is the product, not another calendar. {{s1}}",
    gtm: 5,
    gtmNote: "Teacher associations and local studios that rent rooms to independents.",
    target: "Private music teachers with 15 to 40 weekly students.",
    competitor: "General scheduling tools already take payments. The differentiation has to be the lesson-specific cancellation rule.",
    pitch: `StudioHold lets a teacher publish one rule: this lesson holds a deposit, and a late cancel forfeits it. Parents accept the rule once. The calendar can stay wherever it is.

If the teacher will not say the rule out loud, the software will not say it for them.`,
    channels: [
      { platform: "Search", name: "YouTube results for music teacher studio business", url: "https://www.youtube.com/results?search_query=music+teacher+studio+business", note: "Search page only.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A cancellation paragraph in plain language." },
      { tier: "Frontend", price: "Policy setup", detail: "You write the rule with them and send it to their current students." },
      { tier: "Core", price: "Low monthly seat", detail: "Acceptance log and deposit link. No second calendar." },
    ],
    whyNow: `Card deposits are easy to accept and awkward to explain. The product is the explanation. {{s1}}`,
    proof: `Competitor count is a high sample prior because calendars are plentiful. That is a reason for a narrow offer, or a pass. {{s1}}`,
    marketGap: `Another calendar is a commodity. A stored acceptance of a forfeiture rule is the only gap worth testing. {{s1}}`,
    executionPlan: `Write the rule with five teachers. If three will not send it, stop. If they will, log acceptances in a form before you build accounts.`,
    uniqueness: 4,
    value: 5,
    triangle: { audience: 7, community: 6, offer: 6 },
    frameworkNote: "Close to a crowded commodity unless the forfeiture rule stays the whole product.",
    requirements: {
      skills: { tech: 2, sales: 3, design: 3, domain: 2 },
      weeklyHours: 8,
      capitalBand: "none",
      risk: "low",
      model: "b2c",
      motion: "saas",
      industries: ["education"],
      mvpWeeks: 2,
      salesIntensity: 3,
      regulatoryLoad: 0,
    },
    sources: sources([]),
    brief: {
      title: "StudioHold",
      slug: "studiohold",
      oneLiner: "A deposit and a no-show rule for private music teachers, without a new calendar.",
      customer: "Private music teachers with 15 to 40 students.",
      problem: "Empty hours happen because the cancellation rule was never accepted in writing.",
      mvp: ["Plain-language rule", "Parent acceptance", "Deposit link"],
      stack: "Next.js, Stripe",
      pricing: "Keep the seat cheap. The setup fee is the real offer.",
      outOfScope: ["A second calendar", "Sheet music store", "Student marketplace"],
    },
  },
  {
    slug: "nightfolio",
    title: "Nightfolio",
    summary: "A night-audit checklist for boutique hotels under forty rooms.",
    daysAgo: 40,
    tags: ["Hospitality", "Checklist", "Night audit"],
    keyword: "hotel night audit checklist",
    volume: 7600,
    growthPct: 20,
    inputs: {
      monthlyVolume: 7600,
      growthPct: 20,
      competitorCount: 5,
      painQuoteCount: 1,
      painSeverityAvg: 3.5,
      buildWeeks: 6,
      capitalBand: "low",
      regulatoryLoad: 0,
      dependencyRisk: 2,
      timingSignals: 2,
    },
    category: "Hospitality",
    market: "B2B",
    capitalBand: "low",
    revenueSymbols: "$$",
    arrLabel: "Unset",
    arrNote: "Property-management systems already close the day. This only wins if the checklist is what the night manager actually misses. {{s1}}",
    gtm: 4,
    gtmNote: "Independent hotel groups of two to five properties. Not chains.",
    target: "Boutique hotels under forty rooms with a human night audit.",
    competitor: "The PMS closes the books. The gap is the exceptions list, and it may already live in the PMS. Open the product before you claim otherwise.",
    pitch: `Nightfolio is the exception list for a small hotel’s night audit: rooms that do not match, deposits still open, a minibar note, a maintenance flag. It is finished when the morning manager can see what was left unresolved.

It should not replace the property system. If the export is painful, the idea is probably a pass.`,
    channels: [
      { platform: "Discussion", name: "Hacker News search for hotel software", url: "https://hn.algolia.com/?q=hotel%20pms", note: "Search page only.", sample: true },
    ],
    offerLadder: [
      { tier: "Lead magnet", price: "Free", detail: "A one-page night-audit exception card." },
      { tier: "Frontend", price: "Two-week audit sit-in", detail: "You fill the card from their exports." },
      { tier: "Core", price: "Per property", detail: "Exception list that survives the shift change." },
    ],
    whyNow: `Small properties still run a human audit because the night is when exceptions show up. That does not mean they want another login. {{s1}}`,
    proof: `Dependency on the property system is the risk. Score it that way until an export is attached. {{s1}}`,
    marketGap: `The gap is unresolved exceptions, not a prettier folio. If the PMS already has a night-audit screen they use, stop. {{s1}}`,
    executionPlan: `Ask one night manager to mark up the free card for seven nights. Build software only for the lines they added by hand.`,
    uniqueness: 5,
    value: 6,
    triangle: { audience: 4, community: 3, offer: 6 },
    frameworkNote: "Audience reach is narrow on purpose. A wide hotel product is a different company.",
    requirements: {
      skills: { tech: 3, sales: 3, design: 2, domain: 4 },
      weeklyHours: 20,
      capitalBand: "low",
      risk: "medium",
      model: "b2b",
      motion: "saas",
      industries: ["hospitality"],
      mvpWeeks: 6,
      salesIntensity: 3,
      regulatoryLoad: 0,
    },
    sources: sources([]),
    brief: {
      title: "Nightfolio",
      slug: "nightfolio",
      oneLiner: "The unresolved-exception list for a boutique hotel night audit.",
      customer: "Boutique hotels under forty rooms.",
      problem: "Morning inherits a night audit that does not say what is still open.",
      mvp: ["Exception card", "Shift handoff", "Morning clear"],
      stack: "Next.js, Postgres",
      pricing: "Per property after a two-week sit-in.",
      outOfScope: ["Replacing the PMS", "Channel management", "Revenue management"],
    },
  },
];

// Fix the accidental bad channel on permitping if TypeScript complains.
// The channel object included a publisher field. Remove it by rebuilding that entry cleanly below if needed.

const photoChecklist: SeedIdeaInput = {
  slug: "site-photo-checklist",
  title: "Site Photo Checklist",
  summary: "A one-page shot list a residential electrician prints before photographing a panel for a quote.",
  daysAgo: 4,
  ideaType: "DIGITAL",
  tags: ["Digital product", "Trades", "Sample inputs"],
  keyword: "electrician site photo checklist",
  volume: 1000,
  growthPct: 12,
  inputs: {
    monthlyVolume: 1000,
    growthPct: 12,
    competitorCount: 4,
    painQuoteCount: 0,
    painSeverityAvg: 3,
    buildWeeks: 1,
    capitalBand: "none",
    regulatoryLoad: 0,
    dependencyRisk: 0,
    timingSignals: 2,
  },
  category: "Digital product",
  market: "B2B",
  capitalBand: "none",
  revenueSymbols: "$",
  arrLabel: "Unset until priced",
  arrNote: "A checklist is not a subscription forecast. Price it after someone pays for the file. {{s1}}",
  gtm: 5,
  gtmNote: "Hand the page to one shop before you design a cover.",
  target: "Owners of residential electrical shops who price from phone photos.",
  competitor: "A notes app and a camera roll. Named products were not fetched for this sample record.",
  pitch: `The quote starts with a photo that is missing the label, the breaker schedule, or the ceiling height. The owner asks for another picture, and the lead goes quiet.

Site Photo Checklist is a printable shot list for that visit: panel cover on, panel cover off, the run, the existing fixture, and a coin for scale. It is a file, not a field-service suite. The shop prints it or pins it in the van.

The searches shown below are sample phrases written for this record. They are not live autocomplete results and they are not customer quotes. {{s1}} Volume on the chart is the same kind of prior used when a keyword provider is absent.

Sell the page by hand first. If a shop will not hand it to a technician, a longer ebook will not fix that.`,
  channels: [
    { platform: "Forum", name: "Electrician Talk", url: "https://www.electriciantalk.com/", note: "Public forum index. No posts were scraped.", sample: true },
  ],
  offerLadder: [
    { tier: "Lead magnet", price: "Free", detail: "The six-shot version on a single card." },
    { tier: "Frontend", price: "Set after the first sale", detail: "The full shot list plus a quote cover sheet, delivered as a PDF." },
    { tier: "Core", price: "Set after the first sale", detail: "A small pack: shot list, allowance lines, and a follow-up text." },
  ],
  whyNow: "Phone photos are already how homeowners describe a panel. A checklist can ride that habit without new software. That is a production note, not a market-size claim. {{s1}}",
  proof: "No verbatim quotes are attached. The sample searches are phrases we wrote so this page can show the evidence block. Do not cite them as Google suggestions. {{s1}}",
  marketGap: "Scheduling apps assume the job is already sold. The gap to test is the ten minutes of photos before the number. Confirm substitutes by opening them, not from this paragraph.",
  executionPlan: "Day 1: print the list and ride along on two quotes. Days 2–3: delete any shot the technician skipped. Day 4: sell the PDF to the shop that used it.",
  uniqueness: 5,
  value: 7,
  triangle: { audience: 5, community: 5, offer: 7 },
  frameworkNote: "A digital product sits lower on uniqueness than a workflow app. The offer is clear because the artifact is one page.",
  requirements: {
    skills: { tech: 1, sales: 3, design: 3, domain: 4 },
    weeklyHours: 6,
    capitalBand: "none",
    risk: "low",
    model: "b2b",
    motion: "either",
    industries: ["trades"],
    mvpWeeks: 1,
    salesIntensity: 3,
    regulatoryLoad: 0,
  },
  sources: sources([
    { id: 2, title: "Electrician Talk", url: "https://www.electriciantalk.com/", publisher: "Electrician Talk", accessed: ACCESSED, note: "Public homepage only.", sample: true },
  ]),
  brief: {
    title: "Site Photo Checklist",
    slug: "site-photo-checklist",
    oneLiner: "A printable shot list for pricing a residential panel from photos.",
    customer: "Owners of small residential electrical shops.",
    problem: "Quotes wait on a second round of photos because the first set missed the panel label.",
    mvp: ["Six required shots", "A scale note", "A quote cover line"],
    stack: "A PDF",
    pricing: "Set after the first shop pays.",
    outOfScope: ["A mobile app", "A price book", "Dispatch"],
  },
  searchEvidence: {
    niche: "residential electrician",
    country: "US",
    language: "en",
    source: "sample",
    dataMode: "SAMPLE",
    asOf: ACCESSED,
    note: "Sample phrases written for this record so the searches block has something to show. They are not Google autocomplete results.",
    volume: null,
    volumeNote: null,
    suggestions: [
      { text: "how to photograph an electrical panel for a quote", kind: "question", cluster: "panel photos" },
      { text: "how many photos should an electrician send with a quote", kind: "question", cluster: "panel photos" },
      { text: "electrician missing photo problem on site", kind: "problem", cluster: "missing photos" },
      { text: "electrician quote delayed because photos were blurry", kind: "problem", cluster: "blurry photos" },
      { text: "best electrician site photo checklist", kind: "desire", cluster: "site photo checklist" },
      { text: "electrician panel photo checklist printable", kind: "desire", cluster: "site photo checklist" },
    ],
  },
};

export function seedIdeaRecords() {
  return [...ideas, photoChecklist].map((idea) => {
    const cleaned = {
      ...idea,
      channels: idea.channels.map((channel) => ({
        platform: channel.platform,
        name: channel.name,
        url: channel.url,
        note: channel.note,
        sample: channel.sample,
      })),
    };
    return buildSeedIdea(cleaned);
  });
}

export const queuedIdea = buildSeedIdea({
  slug: "intake-bench",
  title: "Intake Bench",
  summary: "A sample queue candidate: sample intake for an independent testing lab. Waiting on human review.",
  daysAgo: 0,
  status: "QUEUED",
  pitch: `Intake Bench is a review-queue draft for independent testing labs. The clipboard at the bench is the whole product until a reviewer attaches a real source.\n\nDo not publish this record as-is. {{s1}}`,
  tags: ["Needs review", "Labs", "Sample inputs"],
  keyword: "lab sample intake queue",
  volume: 1000,
  growthPct: 12,
  inputs: {
    monthlyVolume: 1000,
    growthPct: 12,
    competitorCount: 4,
    painQuoteCount: 0,
    painSeverityAvg: 3,
    buildWeeks: 4,
    capitalBand: "low",
    regulatoryLoad: 2,
    dependencyRisk: 1,
    timingSignals: 1,
  },
  category: "Labs",
  market: "B2B",
  capitalBand: "low",
  revenueSymbols: "$",
  arrLabel: "Unset",
  arrNote: "Queued draft. Do not publish until a reviewer attaches a real source. {{s1}}",
  gtm: 3,
  gtmNote: "Not researched.",
  target: "Independent testing labs.",
  competitor: "Unknown in this draft.",
  channels: [],
  offerLadder: [
    { tier: "Lead magnet", price: "Free", detail: "A bench checklist." },
    { tier: "Frontend", price: "Unset", detail: "Concierge intake for a week." },
    { tier: "Core", price: "Unset", detail: "Queue software." },
  ],
  whyNow: "This draft is in the queue because sample signals clustered on lab intake. That is not a publish decision. {{s1}}",
  proof: "No quotes attached.",
  marketGap: "Competitors were not fetched.",
  executionPlan: "Reviewer: open the lab’s current intake sheet before approving.",
  uniqueness: 5,
  value: 5,
  triangle: { audience: 4, community: 3, offer: 4 },
  frameworkNote: "Placeholder marks for the reviewer.",
  requirements: {
    skills: { tech: 3, sales: 3, design: 2, domain: 4 },
    weeklyHours: 20,
    capitalBand: "low",
    risk: "medium",
    model: "b2b",
    motion: "saas",
    industries: ["labs"],
    mvpWeeks: 4,
    salesIntensity: 3,
    regulatoryLoad: 2,
  },
  sources: sources([]),
  brief: {
    title: "Intake Bench",
    slug: "intake-bench",
    oneLiner: "A queue for samples arriving at an independent lab.",
    customer: "Independent testing labs.",
    problem: "Intake is a clipboard.",
    mvp: ["Arrival log", "Owner", "Status"],
    stack: "Next.js, Postgres",
    pricing: "Unset.",
    outOfScope: ["Instrument integration", "Regulatory filings"],
  },
});
